kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-ssd
  annotations:
    volume.beta.kubernetes.io/storage-class: ssd-storage-class
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
