apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "main-api.fullname" . }}
  labels:
{{ include "main-api.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "main-api.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "main-api.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-app
              containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http-app
          readinessProbe:
            httpGet:
              path: /
              port: http-app
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV }}
            - name: MONGO_URI
              value: {{ .Values.env.MONGO_URI }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: {{ .Values.env.GOOGLE_APPLICATION_CREDENTIALS }}