apiVersion: v1
kind: Service
metadata:
  name: {{ include "main-api.fullname" . }}
  labels:
    {{- include "main-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      # name: http
  selector:
    app.kubernetes.io/name: {{ include "coachx-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  # selector:
  #   {{- include "main-api.selectorLabels" . | nindent 4 }}
